QUESTION1_RUS = 'Вы живете один/одна? '
QUESTION_KIDS_RUS = 'У Вас есть дети? '
STATUS_SUBJECT_RUS = 'субъект'
STATUS_COUPLE_RUS = 'семейная пара'
STATUS_LONEPAR_RUS = 'родитель-одиночка'
INCOME_DIFFER_RUS = 'Ваш доход различается от месяца к месяцу? '
AV_MON_INCOME_RUS = 'Каков Ваш приблизительный месячный доход? '
LIST_MONTHS_RUS = ['январе', 'феврале', 'марте', 'апреле', 'мае', 'июне', 'июле', 'августе', 'сентябре', 'октябре',
                   'ноябре', 'декабре']
EST_MON_INCOME_RUS = 'Каков Ваш приблизительный доход в {}? '
INCOME_BETWEEN_RUS = 'Годовой доход находится между {:,} и {:,} рублями и равен {:,} рублей.'
ANN_TAX_RUS = 'Годовой налог равен {:,.2f} рублей.'
BIG_INCOME_RUS = 'Годовой доход выше {:,} рублей и равен {:,} рублей.'
YOUR_INCOME_RUS = 'Ваш годовой доход, рублей'
RELEVANT_TAX_RATES_RUS = 'Соответствующие налоговые ставки'
PLOT_TITLE_RUS = 'Начисление налога по прогрессивной системе налогообложения в зависимости от Вашего дохода'
STATUS_HEADING_RUS = 'Статус пользователя: {}\n'
TAX_HEADING_RUS = 'Ваш годовой налог: {:,.2f} рублей'
DEDUCTION_RUS = 'Ваш годовой налоговый вычет: '

question1 = QUESTION1_RUS
question_kids = QUESTION_KIDS_RUS
status_lonepar = STATUS_LONEPAR_RUS
status_subject = STATUS_SUBJECT_RUS
status_couple = STATUS_COUPLE_RUS
income_differ = INCOME_DIFFER_RUS
av_mon_income = AV_MON_INCOME_RUS
list_months = LIST_MONTHS_RUS
est_mon_income = EST_MON_INCOME_RUS
income_between = INCOME_BETWEEN_RUS
ann_tax = ANN_TAX_RUS
big_income = BIG_INCOME_RUS
your_income = YOUR_INCOME_RUS
relevant_tax_rates = RELEVANT_TAX_RATES_RUS
plot_title = PLOT_TITLE_RUS
status_heading = STATUS_HEADING_RUS
tax_heading = TAX_HEADING_RUS
deduction = DEDUCTION_RUS
