QUESTION1_ENG = 'Do you live alone? '
QUESTION_KIDS_ENG = 'Do you have kids? '
STATUS_SUBJECT_ENG = 'subject'
STATUS_COUPLE_ENG = 'couple'
STATUS_LONEPAR_ENG = 'lone parent'
INCOME_DIFFER_ENG = 'Does your income differ from month to month? '
AV_MON_INCOME_ENG = 'What is your average month income? '
LIST_MONTHS_ENG = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
                   'November', 'December']
EST_MON_INCOME_ENG = 'What is your estimated income in {}? '
INCOME_BETWEEN_ENG = '\nThe annual income is between {:,} and {:,} rubbles and equals {:,} rubbles.'
ANN_TAX_ENG = 'The annual tax equals {:,.2f} rubbles.'
BIG_INCOME_ENG = '\nThe annual income exceeds {:,} rubbles and equals {:,} rubbles.'
YOUR_INCOME_ENG = 'Your annual income, rubbles'
RELEVANT_TAX_RATES_ENG = 'Relevant tax rates'
PLOT_TITLE_ENG = 'Progressive taxation depending on your income'
STATUS_HEADING_ENG = 'User`s status: {}\n'
TAX_HEADING_ENG = 'Your annual tax: {:,.2f} rubbles'
DEDUCTION_ENG = 'The amount of tax to deduce annually: '
SAVE_OR_SHOW_ENG = '\nWould you like to show or save the plot? '

question1 = QUESTION1_ENG
question_kids = QUESTION_KIDS_ENG
status_lonepar = STATUS_LONEPAR_ENG
status_subject = STATUS_SUBJECT_ENG
status_couple = STATUS_COUPLE_ENG
income_differ = INCOME_DIFFER_ENG
av_mon_income = AV_MON_INCOME_ENG
list_months = LIST_MONTHS_ENG
est_mon_income = EST_MON_INCOME_ENG
income_between = INCOME_BETWEEN_ENG
ann_tax = ANN_TAX_ENG
big_income = BIG_INCOME_ENG
your_income = YOUR_INCOME_ENG
relevant_tax_rates = RELEVANT_TAX_RATES_ENG
plot_title = PLOT_TITLE_ENG
status_heading = STATUS_HEADING_ENG
tax_heading = TAX_HEADING_ENG
deduction = DEDUCTION_ENG
save_or_show = SAVE_OR_SHOW_ENG
